# Generated by Django 4.2.6 on 2023-10-14 10:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                ("session_name", models.CharField(default="", max_length=500)),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finished_at",
                    models.CharField(default="not stored", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("easy_questions", models.CharField(default="", max_length=1000)),
                ("med_questions", models.CharField(default="", max_length=1000)),
                ("hard_questions", models.CharField(default="", max_length=1000)),
                ("score", models.IntegerField()),
                (
                    "assesment_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.studysession",
                    ),
                ),
            ],
        ),
    ]
