# Generated by Django 4.2.6 on 2023-10-15 00:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(default="", max_length=100)),
                ("topic", models.CharField(default="", max_length=100)),
                ("score", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                ("session_name", models.CharField(default="", max_length=500)),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("pdf_file", models.FileField(upload_to="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finished_at",
                    models.CharField(default="not stored", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mcq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(default="", max_length=100)),
                ("gen_question", models.CharField(default="", max_length=2000)),
                ("is_correct", models.BooleanField(default="", null=True)),
                ("time_taken", models.IntegerField(default="", null=True)),
                (
                    "difficulty_score",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "assesment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.assessment"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="assesment_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.studysession"
            ),
        ),
    ]
