# Generated by Django 4.2.6 on 2023-10-14 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studysession",
            old_name="file",
            new_name="pdf_file",
        ),
    ]
