# Generated by Django 4.2.6 on 2023-10-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_assessment_session_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessment",
            name="easy_questions",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="hard_questions",
        ),
        migrations.RemoveField(
            model_name="assessment",
            name="med_questions",
        ),
        migrations.AddField(
            model_name="assessment",
            name="topic",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="session_id",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.CreateModel(
            name="Mcq_questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assessment_id", models.CharField(default="", max_length=100)),
                ("gen_question", models.CharField(default="", max_length=2000)),
                ("is_correct", models.BooleanField()),
                ("time_taken", models.IntegerField()),
                ("difficulty_score", models.IntegerField()),
                (
                    "assesment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.assessment"
                    ),
                ),
            ],
        ),
    ]
