# Generated by Django 4.2.6 on 2023-10-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_assessment_score_alter_mcq_difficulty_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcq",
            name="difficulty_score",
            field=models.DecimalField(
                decimal_places=2, default="", max_digits=4, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mcq",
            name="is_correct",
            field=models.BooleanField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="mcq",
            name="time_taken",
            field=models.IntegerField(default="", null=True),
        ),
    ]
